In [1]:
import numpy as np

###`Q-1:` Find the nearest element in the array to a given integer.
```
Ex:-
a=23 and array - [10 17 24 31 38 45 52 59].
Nearest element is 24
```
Hint: Read about this function `argmin()`

In [8]:
# code here
arr = np.array([10 ,17 ,24 ,31 ,38 ,45 ,52 ,59])
a=23
# arr.sort()
# arr[arr>23][0]
arr[np.abs((arr-a)).argmin()]

24

###`Q-2:` Replace multiples of 3 or 5 as 0 in the given array.
```
arr=[1 2 3 4 5 6 7 9]

result-> [1 2 0 4 0 0 7 0]
```

In [13]:
# code here
arr=np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,9])
# np.where((arr%3==0)|(arr%5==0),0,arr)
arr[(arr%3==0)|(arr%5==0)]=0
arr

array([1, 2, 0, 4, 0, 0, 7, 0])

###`Q-3:` Use Fancy Indexing.
1. Double the array elements at  given indexes
```
arr = np.arrange(10)
indexes = [0,3,4,9]
```
Result -> `[ 0  1  2  6  8  5  6  7  8 18]`

2. Using a given array make a different array as in below example
```
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
```
* Internal-repetion should be as length of the array.

Hint:
```
if a is an array
a = [2,4]
a[[1,1,0,1]] will result in-> [4 4 2 4]
```

In [23]:
# code here
arr = np.arange(10,dtype='i4')
indexes = [0,3,4,9]
# array = [1,2,3]
# result array -> [1 1 1 2 2 2 3 3 3]
arr[indexes]=arr[indexes]*2
arr
# np.array()
# array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
#       like=None)

# np.com_stack(arr)

array([ 0,  1,  2,  6,  8,  5,  6,  7,  8, 18], dtype=int32)

###`Q-4:` Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the array.
```
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])

```

In [ ]:
# code here


### `Q-5:` Write a NumPy program

- to find the missing data in a given array. Return a boolean matrix.
- also try to fill those missing values with 0. For that, you can use `np.nan_to_num(a)`

```python
import numpy as np

np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
```

In [ ]:
# code here

###`Q-6:` Given two arrays, X and Y, construct the Cauchy matrix C.
`Cij =1/(xi - yj)`

http://en.wikipedia.org/wiki/Cauchy_matrix
```
x = numpy.array([1,2,3,4]).reshape((-1, 1)
y = numpy.array([5,6,7])
```

In [ ]:
# code here

###`Q-7:` Plot this below equation.

$$\large y = \frac{e^x - e^{-x}}{e^x + e^{-x}}$$

**Note: This equation is called tanh activation function. In deep learning, many times this function is used. If you find some difference between the sigmoid function and this tanh function, note that to your notebook.**

In [ ]:
# code here

### `Q-8:` Plot the below equation.

$$\large y = \sqrt{36 - (x - 4)^2} + 2$$

The range of x should be between -2 to 10. $x ∈ [-2, 10]$



In [ ]:
# code here

### `Q-9:` Write a program implement Boradcasting Rule to check if two array can be added or not.
Given tuples of shapes.
```
shape of a- (3,2,2)
shape of b- (2,2)

check_broadcast(a, b) -> return Boolean (True if can broadcasted, False other wise.)
```

In [ ]:
# code here

In [28]:
dt=np.dtype([('age',np.int8)])
a=np.array([10,20,300],dtype=dt)
a['age']

/var/folders/rs/nwdm5_tx1yx4mc85mxl32bx40000gn/T/ipykernel_27894/2639549719.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a=np.array([10,20,300],dtype=dt)


array([10, 20, 44], dtype=int8)

In [30]:
a = np.dtype(np.uint32)
type(a)

numpy.dtypes.UInt32DType

In [33]:
a = np.arange(11*12).reshape(11,12)
np.unravel_index(100,(11,12))
a.ndim

2